from aiogram import Router

router = Router()

sent_message_add_screen_ids = {}

adminAccountPicture = 'AgACAgIAAxkBAAIBVWdXA_cNc-oo7pUZ_FWC-raGEzSeAAIF6TEb8365Sq0edrJcGxpdAQADAgADeQADNgQ'
adminViewUsersPicture = 'AgACAgIAAxkBAAIBYWdXCWByRki7fKqbcR1jhagAAc7_1gACZekxG_N-uUqNte1B85bxKQEAAwIAA3kAAzYE'
adminManagePicture = 'AgACAgIAAxkBAAIComdXiefWFFFW74I7hJHjl3f6ivdgAAKU7DEb8365SqrGUX6nlQGSAQADAgADeQADNgQ'